dist: focal
language: go

go:
  - 1.15.x
  - 1.14.x
  - 1.13.x

env:
  - GO111MODULE=on
#  - GOMODULE=https://goproxy.cn,direct

script:
  - go test -v

notifications:
  email:
    recipients:
      - 1586616064@qq.com
    on_success: always
    on_failure: always
    on_error: always